DROP TABLE IF EXISTS "Presence" CASCADE;
DROP TABLE IF EXISTS "Division" CASCADE;
DROP TABLE IF EXISTS "TypeDeMatch" CASCADE;
DROP TABLE IF EXISTS "MatchDeSoccer" CASCADE;
DROP TABLE IF EXISTS "Facture" CASCADE;
DROP TABLE IF EXISTS "Remplace" CASCADE;
DROP TABLE IF EXISTS "Indisponibilite" CASCADE;
DROP TABLE IF EXISTS "Saison" CASCADE;
DROP TABLE IF EXISTS "Equipe" CASCADE;
DROP TABLE IF EXISTS "Joueur" CASCADE;
DROP TABLE IF EXISTS "Membre" CASCADE;
DROP TABLE IF EXISTS "NomSaison" CASCADE;

DROP TYPE IF EXISTS uint2;
